import type { PulseOverlay } from "@/lib/config-model";
import { syncOverlayFlags } from "@/lib/config-model";

export type ConfigPreset = {
  id: string;
  name: string;
  hint: string;
  sl: number;
  minStep: number;
  stepMax: number;
  trail: string;
  minPf: number;
  maxDdS: number;
  patch: Partial<PulseOverlay>;
};

const SHARED: Partial<PulseOverlay> = {
  blockEnabled: true,
  stratBlock: true,
  blockMaxStack: 3,
  blockVolumeRatio: 1,
  blockProfitFactorRatio: 1.1,
  dcaEnabled: false,
  stratDca: false,
  controlOrders: true,
  histEnabled: true,
  setUseHistoricGate: true,
  setStrictGate: true,
  setAutoDeact: true,
  setReactivate: true,
  setMinSamples: 12,
  exitEnabled: true,
  exitIgnoreTp: true,
  exitBestOf: true,
  exitLockOn: true,
  exitPeakOn: true,
  indEnabled: true,
  stratIndications: true,
  axisPrevEnabled: true,
  axisLastEnabled: true,
  axisContEnabled: true,
  axisPauseEnabled: true,
  slToTpAuto: true,
  trailAuto: true,
  trailRecalcGive: true,
};

export const CONFIG_PRESETS: ConfigPreset[] = [
  {
    id: "tight-guard",
    name: "Tight Guard",
    hint: "Lowest SL 0.3 · min step 12 · 20h · max DD 15m",
    sl: 0.3,
    minStep: 12,
    stepMax: 18,
    trail: "0.3:0.1",
    minPf: 1.12,
    maxDdS: 900,
    patch: {
      ...SHARED,
      slToTpRatio: 0.3,
      slMinPct: 0.2,
      slMaxPct: 0.6,
      setMinStep: 12,
      setStepMax: 18,
      stratTrailing: true,
      trailArmPct: 0.3,
      trailGivePct: 0.1,
      trailArmMin: 0.3,
      trailArmMax: 0.3,
      setMinPf: 1.12,
      minPf: 1.12,
      baseMinPf: 1.08,
      mainMinPf: 1.1,
      realMinPf: 1.12,
      setMaxDdTimeS: 900,
      maxDdTimeS: 900,
      histLookbackBars: 1200,
      stratGeneral: true,
    },
  },
  {
    id: "low-dd-core",
    name: "Low DD Core",
    hint: "SL 0.6 · step 10–16 · trail 0.6:0.2 · 20h",
    sl: 0.6,
    minStep: 10,
    stepMax: 16,
    trail: "0.6:0.2",
    minPf: 1.1,
    maxDdS: 1200,
    patch: {
      ...SHARED,
      slToTpRatio: 0.6,
      slMinPct: 0.2,
      slMaxPct: 0.8,
      setMinStep: 10,
      setStepMax: 16,
      stratTrailing: true,
      trailArmPct: 0.6,
      trailGivePct: 0.2,
      trailArmMin: 0.6,
      trailArmMax: 0.6,
      setMinPf: 1.1,
      minPf: 1.1,
      baseMinPf: 1.05,
      mainMinPf: 1.08,
      realMinPf: 1.1,
      setMaxDdTimeS: 1200,
      maxDdTimeS: 1200,
      histLookbackBars: 1200,
      stratGeneral: true,
    },
  },
  {
    id: "balanced-coord",
    name: "Balanced Coord",
    hint: "Both packs · axes on · SL 0.6 · step 8–16",
    sl: 0.6,
    minStep: 8,
    stepMax: 16,
    trail: "0.6:0.2",
    minPf: 1.1,
    maxDdS: 1800,
    patch: {
      ...SHARED,
      slToTpRatio: 0.6,
      setMinStep: 8,
      setStepMax: 16,
      stratTrailing: true,
      trailArmPct: 0.6,
      trailGivePct: 0.2,
      trailArmMin: 0.6,
      trailArmMax: 0.6,
      setMinPf: 1.1,
      minPf: 1.1,
      baseMinPf: 1.05,
      mainMinPf: 1.08,
      realMinPf: 1.1,
      setMaxDdTimeS: 1800,
      histLookbackBars: 720,
      stratGeneral: true,
    },
  },
  {
    id: "trail-scout",
    name: "Trail Scout",
    hint: "Low SL 0.3 · trail 0.3–0.9 · step 10–18",
    sl: 0.3,
    minStep: 10,
    stepMax: 18,
    trail: "0.3:0.1",
    minPf: 1.1,
    maxDdS: 1200,
    patch: {
      ...SHARED,
      slToTpRatio: 0.3,
      setMinStep: 10,
      setStepMax: 18,
      stratTrailing: true,
      trailArmPct: 0.3,
      trailGivePct: 0.1,
      trailArmMin: 0.3,
      trailArmMax: 0.9,
      setMinPf: 1.1,
      minPf: 1.1,
      setMaxDdTimeS: 1200,
      histLookbackBars: 1200,
      stratGeneral: true,
    },
  },
  {
    id: "indication-lead",
    name: "Indication Lead",
    hint: "Indications only · agreement 0.7 · SL 0.6",
    sl: 0.6,
    minStep: 10,
    stepMax: 18,
    trail: "0.6:0.2",
    minPf: 1.1,
    maxDdS: 1500,
    patch: {
      ...SHARED,
      slToTpRatio: 0.6,
      setMinStep: 10,
      setStepMax: 18,
      stratTrailing: true,
      trailArmPct: 0.6,
      trailGivePct: 0.2,
      trailArmMin: 0.6,
      trailArmMax: 0.6,
      stratGeneral: false,
      stratIndications: true,
      indMinAgreement: 0.7,
      indMinConfidence: 0.65,
      setMinPf: 1.1,
      minPf: 1.1,
      setMaxDdTimeS: 1500,
      histLookbackBars: 1200,
    },
  },
  {
    id: "block-stack",
    name: "Block Stack",
    hint: "Block stack 3 · vr 1 · SL 0.6 · DCA off",
    sl: 0.6,
    minStep: 8,
    stepMax: 14,
    trail: "0.6:0.2",
    minPf: 1.08,
    maxDdS: 1800,
    patch: {
      ...SHARED,
      slToTpRatio: 0.6,
      setMinStep: 8,
      setStepMax: 14,
      stratTrailing: true,
      trailArmPct: 0.6,
      trailGivePct: 0.2,
      blockMaxStack: 3,
      blockVolumeRatio: 1,
      setMinPf: 1.08,
      minPf: 1.1,
      setMaxDdTimeS: 1800,
      histLookbackBars: 720,
      stratGeneral: true,
    },
  },
  {
    id: "strict-gate",
    name: "Strict Gate",
    hint: "PF 1.10/1.12/1.15 · SL 0.3 · max DD 10m",
    sl: 0.3,
    minStep: 12,
    stepMax: 22,
    trail: "0.3:0.1",
    minPf: 1.15,
    maxDdS: 600,
    patch: {
      ...SHARED,
      slToTpRatio: 0.3,
      setMinStep: 12,
      setStepMax: 22,
      stratTrailing: true,
      trailArmPct: 0.3,
      trailGivePct: 0.1,
      trailArmMin: 0.3,
      trailArmMax: 0.3,
      baseMinPf: 1.1,
      mainMinPf: 1.12,
      realMinPf: 1.15,
      setMinPf: 1.15,
      minPf: 1.15,
      setMaxDdTimeS: 600,
      maxDdTimeS: 600,
      histLookbackBars: 1200,
      stratGeneral: true,
    },
  },
  {
    id: "wide-scan",
    name: "Wide Scan",
    hint: "Both packs · step 8–22 · full trail · 20h",
    sl: 0.6,
    minStep: 8,
    stepMax: 22,
    trail: "0.6:0.2",
    minPf: 1.08,
    maxDdS: 1800,
    patch: {
      ...SHARED,
      slToTpRatio: 0.6,
      setMinStep: 8,
      setStepMax: 22,
      stratTrailing: true,
      trailArmPct: 0.6,
      trailGivePct: 0.2,
      trailArmMin: 0.3,
      trailArmMax: 1.5,
      setMinPf: 1.08,
      minPf: 1.1,
      setMaxDdTimeS: 1800,
      histLookbackBars: 1200,
      stratGeneral: true,
    },
  },
];

export function applyPresetPatch(base: PulseOverlay, id: string): PulseOverlay {
  const preset = CONFIG_PRESETS.find((p) => p.id === id);
  if (!preset) return base;
  return syncOverlayFlags({ ...base, ...preset.patch });
}
